### PR TITLE
fix: defer reading of database configuration until needed to fix race

### LINKED ISSUE #1313: Race condition in config loading prevents connection to mongoDB
**Describe the bug**
We've recently developed a race condition where the the database adaptors are being initialised on the default configuration, just before the user configuration is loaded. This results in always loading the neDB adaptor and failing to connect to mongo (when configured to do so). 

This is likely the result of recent changes to move to an es module setup. 

**To Reproduce**

1. Create a config that will load mongo, 
     - e.g. `cp proxy.config.json proxy.config.mongo.json` then edit the sink config to disable fd and enable mongo.
2. Add some console.log statements in src/db/index.ts to identify which DB adaptor is being loaded.
3. Add some console.log statements in src/config/index.ts to output the config at the end of `loadFullConfiguration()`
4. Build to dist (`npm run build`)
5. Run with a config file set via commandline arg: 
    - `cd dist`
    - node index.js --config ../proxy.config.mongo.json
6. Check the output - note that the config outputs a couple of times, once with the default config and again with the user config. The database adaptor is loaded between these two on the default config.

**Expected behavior**

User config is loaded before the database adaptor is initialised.

### PR DESCRIPTION
**Pull request by kriswest**
resolves #1313
supercedes #1314 

By deferring the setup of the database adaptors until they are first used, we can defer the retrieval of the DB config allowing the user configuration to be loaded before we attempt to use it.

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -4,11 +4,12 @@ import path from 'path';
...
 import * as fs from 'fs';
-import { configFile, setConfigFile, validate } from './src/config/file';
+import { getConfigFile, setConfigFile, validate } from './src/config/file';
 import { initUserConfig } from './src/config';
-import Proxy from './src/proxy';
-import service from './src/service';
+import * as Proxy from './src/proxy';
+import * as Service from './src/service';
 
+console.log('handling commandline args');
```
Comment (kriswest) [inline index.ts]:
```suggestion
```

File: index.ts [hunk 2]
```diff
@@ -46,10 +49,14 @@ if (argv.v) {
...
 }
 
+console.log('validating config');
 validate();
 
-const proxy = new Proxy();
+console.log('Setting up the proxy and Service');
+
+// The deferred imports should cause these to be loaded on first access
+const proxy = new Proxy.Proxy();
```
Comment (kriswest) [inline index.ts]:
```suggestion
const proxy = new Proxy();
```

File: index.ts [hunk 3]
```diff
@@ -46,10 +49,14 @@ if (argv.v) {
...
 proxy.start();
-service.start(proxy);
+Service.Service.start(proxy);
```
Comment (kriswest) [inline index.ts]:
```suggestion
Service.start(proxy);
```

File: index.ts [hunk 4]
```diff
@@ -4,11 +4,12 @@ import path from 'path';
 import yargs from 'yargs';
 import { hideBin } from 'yargs/helpers';
 import * as fs from 'fs';
-import { configFile, setConfigFile, validate } from './src/config/file';
+import { getConfigFile, setConfigFile, validate } from './src/config/file';
 import { initUserConfig } from './src/config';
-import Proxy from './src/proxy';
-import service from './src/service';
+import * as Proxy from './src/proxy';
+import * as Service from './src/service';
```
Comment (kriswest) [inline index.ts]:
```suggestion
import { Proxy } from './src/proxy';
import { Service } from './src/service';
```

File: src/db/file/pushes.ts [hunk 5]
```diff
@@ -1,17 +1,14 @@
-import fs from 'fs';
 import _ from 'lodash';
 import Datastore from '@seald-io/nedb';
 import { Action } from '../../proxy/actions/Action';
 import { toClass } from '../helper';
 import { PushQuery } from '../types';
+import { initializeFolders } from './helper';
```
Comment (coopernetes) [inline src/db/file/pushes.ts]: Remove unused import.
```suggestion
```

File: src/db/file/helper.ts [hunk 6]
```diff
@@ -1 +1,7 @@
+import { existsSync, mkdirSync } from 'fs';
+
 export const getSessionStore = (): undefined => undefined;
+export const initializeFolders = () => {
+  if (!existsSync('./.data')) mkdirSync('./.data');
+  if (!existsSync('./.data/db')) mkdirSync('./.data/db');
```
Comment (coopernetes) [inline src/db/file/helper.ts]: Equivalent to `mkdir -p`

https://nodejs.org/api/fs.html#fsmkdirsyncpath-options

```suggestion
  if (!existsSync('./.data/db')) mkdirSync('./.data/db', { recursive: true });
```

File: src/db/index.ts [hunk 7]
```diff
@@ -6,13 +6,28 @@ import * as mongo from './mongo';
...
+    if (config.getDatabase().type === 'mongo') {
+      console.log('Loading MongoDB database adaptor');
+      _sink = mongo;
+    } else if (config.getDatabase().type === 'fs') {
+      console.log('Loading neDB database adaptor');
+      initializeFolders();
+      _sink = neDb;
+    }
+  }
+  return _sink!;
```
Comment (coopernetes) [inline src/db/index.ts]: Removes the `!` and only returns an initialized sink for supported database types.

```suggestion
    } else {
      console.error(`Unsupported database type: ${config.getDatabase().type}`);
      process.exit(1);
    }
  }
  return _sink;
```

File: src/db/index.ts [hunk 8]
```diff
@@ -82,6 +98,8 @@ export const createRepo = async (repo: AuthorisedRepo) => {
   };
   toCreate.name = repo.name.toLowerCase();
 
+  start();
+
```
Comment (kriswest) [inline src/db/index.ts]:
```suggestion
```

File: src/proxy/actions/Action.ts [hunk 9]
```diff
@@ -151,4 +151,4 @@ class Action {
   }
 }
 
-export { Action };
+export { Action, CommitData };
```
Comment (kriswest) [inline src/proxy/actions/Action.ts]:
```suggestion
export { Action };
```

File: test/processors/checkAuthorEmails.test.ts [hunk 10]
```diff
@@ -3,7 +3,7 @@ import { exec } from '../../src/proxy/processors/push-action/checkAuthorEmails';
 import { Action } from '../../src/proxy/actions';
 import * as configModule from '../../src/config';
 import * as validator from 'validator';
-import { Commit } from '../../src/proxy/actions/Action';
+import { CommitData } from '../../src/proxy/actions/Action';
```
Comment (kriswest) [inline test/processors/checkAuthorEmails.test.ts]:
```suggestion
import { CommitData } from '../../src/proxy/processors/types';
```

File: src/db/file/pushes.ts [hunk 11]
```diff
@@ -9,9 +8,6 @@ const COMPACTION_INTERVAL = 1000 * 60 * 60 * 24; // once per day
 
 // these don't get coverage in tests as they have already been run once before the test
 /* istanbul ignore if */
```
Comment (jescalada) [inline src/db/file/pushes.ts]: Is this `/* istanbul ignore if */` directive doing something or should we remove it? 🤔

File: test/processors/getDiff.test.ts
Comment (jescalada) [inline test/processors/getDiff.test.ts:1]: Thanks for fixing up this one - I totally missed it during the Vitest refactors!

We could replace the `00000...` strings with the `EMPTY_COMMIT_HASH` constant in `src/proxy/processors/constants.ts`.

File: test/proxy.test.ts
Comment (jescalada) [inline test/proxy.test.ts:1]: These tests might need the `getAllProxiedHosts` function to pass if the `.skip` is removed:

```ts
const mockDb = {
  getRepos: vi.fn().mockResolvedValue([]),
  createRepo: vi.fn().mockResolvedValue(undefined),
  addUserCanPush: vi.fn().mockResolvedValue(undefined),
  addUserCanAuthorise: vi.fn().mockResolvedValue(undefined),
  getAllProxiedHosts: vi.fn().mockResolvedValue([]),
};
```

and

```ts
vi.doMock('../src/db', () => ({
  getRepos: mockDb.getRepos,
  createRepo: mockDb.createRepo,
  addUserCanPush: mockDb.addUserCanPush,
  addUserCanAuthorise: mockDb.addUserCanAuthorise,
  getAllProxiedHosts: mockDb.getAllProxiedHosts,
}));
```

File: test/proxy.test.ts [hunk 12]
```diff
@@ -105,7 +105,7 @@ describe.skip('Proxy Module TLS Certificate Loading', () => {
     process.env.NODE_ENV = 'test';
```
Comment (jescalada) [inline test/proxy.test.ts]:
```suggestion
```

File: test/proxy.test.ts [hunk 13]
```diff
@@ -105,7 +105,7 @@ describe.skip('Proxy Module TLS Certificate Loading', () => {
...
     process.env.GIT_PROXY_HTTPS_SERVER_PORT = '8443';
```
Comment (jescalada) [inline test/proxy.test.ts]: I believe these lines aren't really doing anything - good to remove!

```suggestion
```

File: test/proxy.test.ts [hunk 14]
```diff
@@ -105,7 +105,7 @@ describe.skip('Proxy Module TLS Certificate Loading', () => {
...
```
Comment (jescalada) [inline test/proxy.test.ts]: I did some testing here while trying to remove the `.skip`, and although I couldn't find a proper fix, I did find a way to sweep the errors under the rug:

```suggestion

     vi.doMock('../src/config/env', () => ({
      serverConfig: {
        GIT_PROXY_SERVER_PORT: '8001',
        GIT_PROXY_HTTPS_SERVER_PORT: '8443',
      },
    }));
```

We probably don't want to do this - but it shows that the problem comes from some `Proxy` instance somewhere not closing properly...

**Review by jescalada — APPROVED** [review]
LGTM! 🚀 

I did some testing with the skipped tests just in case, but I'm still getting some mysterious errors with the `testPush.test.ts` file:

<details>

```bash
 FAIL  test/testPush.test.ts > Push API > test push API > should allow an authorizer to approve a push
AssertionError: expected 401 to be 200 // Object.is equality

- Expected
+ Received

- 200
+ 401

 ❯ test/testPush.test.ts:158:26
    156|           },
    157|         });
    158|       expect(res.status).toBe(200);
       |                          ^
    159|     });
    160| 

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/3]⎯

 FAIL  test/testPush.test.ts > Push API > should allow an authorizer to reject a push
AssertionError: expected 401 to be 200 // Object.is equality

- Expected
+ Received

- 200
+ 401

 ❯ test/testPush.test.ts:272:24
    270|       .post(`/api/v1/push/${TEST_PUSH.id}/reject`)
    271|       .set('Cookie', `${cookie}`);
    272|     expect(res.status).toBe(200);
       |                        ^
    273|   });
    274| 

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/3]⎯

 FAIL  test/testPush.test.ts > Push API > should allow a committer to cancel a push
AssertionError: expected 401 to be 200 // Object.is equality

- Expected
+ Received

- 200
+ 401

 ❯ test/testPush.test.ts:316:24
    314|       .post(`/api/v1/push/${TEST_PUSH.id}/cancel`)
    315|       .set('Cookie', `${cookie}`);
    316|     expect(res.status).toBe(200);
       |                        ^
    317| 
    318|     const pushes = await request(app).get('/api/v1/push').set('Cookie', `${cookie…

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[3/3]⎯


 Test Files  1 failed | 45 passed (46)
      Tests  3 failed | 536 passed (539)
```

</details>

Would be great to have some more clues on this!

File: src/db/file/pushes.ts (hunk 11 above)
Comment (kriswest) [inline src/db/file/pushes.ts]:
```suggestion
```

File: test/proxy.test.ts (hunk 14 above)
Comment (kriswest) [reply test/proxy.test.ts]: To track it down we could instrument Proxy and have it record the current time and print a log message with it, then print another on close using the saved start time, then match them up in the output after a test run to find the one that didn't close?

Comment (jescalada) [reply test/proxy.test.ts]: Sounds like a good idea! I'll look into this right after the next release/rc.

Added your tip to the issue 👍🏼 #1294

File: test/proxy.test.ts
Comment (jescalada) [reply test/proxy.test.ts:1]: This will come up again while removing `.skip`s in #1294, so we can probably go ahead and merge this PR.

File: test/processors/getDiff.test.ts
Comment (jescalada) [reply test/processors/getDiff.test.ts:1]: ~~I can handle this myself in the `any`/`as` removal PR I'm working on ATM. 👍🏼~~

Decided to make the fixes here while fixing the CI formatting error.
