### PR TITLE
test: fix Cypress test data dependency

### LINKED ISSUE #978: Cypress tests require data created by mocha tests, but should be self-contained
**Describe the bug**
The cypress tests for the repo page depend on data that is created and abandoned by the mocha tests. I.e. the `test-repo` used here: https://github.com/finos/git-proxy/blob/371894323bae83a2aedb8d2944745544359a6275/cypress/e2e/repo.cy.js#L11-L21

The data is created in a mocha test here: https://github.com/finos/git-proxy/blob/371894323bae83a2aedb8d2944745544359a6275/test/addRepoTest.test.js#L44-L49

Which also has to handle it (perhaps) already existing on run: 
https://github.com/finos/git-proxy/blob/371894323bae83a2aedb8d2944745544359a6275/test/addRepoTest.test.js#L26-L29

Ideally tests should handle their own set-up and tear-down (clean-up). As the cypress tests use client-side JS they can't directly import the DB clients and create the data they need, but they could make API calls or a node script be used for setup and tear down before/after the cypress command.

**Expected behaviour**
Each set of tests handles its own data creation and subsequent clean-up.

**Additional context**

### PR DESCRIPTION
**Pull request by jescalada**
Fixes #978.

### Changelog
- Added CSRF token command to use API through Cypress
- Refactored `repo.cy.js` to generate and tear down repo data

### CODE REVIEW

File: cypress/support/commands.js [hunk 1]
```diff
@@ -39,3 +39,12 @@ Cypress.Commands.add('login', (username, password) => {
     cy.url().should('include', '/dashboard/repo');
   });
 });
+
+Cypress.Commands.add('getCSRFToken', () => {
+  return cy.request('GET', 'http://localhost:8080/api/v1/repo').then((res) => {
+    const cookies = res.headers['set-cookie'];
+    const csrfCookie = cookies.find(c => c.startsWith('csrf='));
+    const token = decodeURIComponent(csrfCookie.split('=')[1].split(';')[0]);
```
Comment (dcoric) [inline cypress/support/commands.js]: This assumes `res.headers['set-cookie']` is present and that a cookie starts with `csrf=`. It would be good to add a guard before running `.split('=')[1]` to avoid runtime errors if something is missing.

**Review by dcoric — CHANGES_REQUESTED** [review]
One small remark, otherwise it looks good.
